name: amica
description: Amica is an App that suppose to connect people with same interests in the area
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.0
  go_router: ^8.0.2
  adaptive_navigation: ^0.0.9
  file_picker: ^5.3.2
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  flutter_launcher_icons: ^0.13.1
  dotted_border: ^2.0.0+3
  reactive_forms: ^16.1.0
  http: ^1.1.0
  path_provider: ^2.1.1
  rx_redux: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/valery_doe.jpg
    - assets/valery_doe_1.jpg
    - assets/valery_doe_2.jpg
    - assets/valery_doe_3.jpg
    - assets/valery_doe_4.jpg
    - assets/girl_1.jpeg
    - assets/girl_1.1.jpeg
    - assets/girl_1.2.jpeg
    - assets/girl_2.jpeg
    - assets/girl_3.jpeg
    - assets/girl_3.1.jpeg
    - assets/guy_1.jpeg
    - assets/guy_2.jpeg
    - assets/guy_3.jpeg
    - assets/guy_3.1.jpeg
    - assets/guy_3.2.jpeg
    - assets/guy_3.3.jpeg
    - assets/mock_users.json
    - assets/mock_interests.json
    - assets/mock_likes.json
    - assets/mock_events.json
    - assets/mock_user_filter.json
    - assets/mock_event_filter.json
    - assets/mock_chat_rooms.json
    - assets/mock_pinned_chat_rooms.json
    - assets/mock_chat_messages.json
    - assets/logo/logo.png
    - assets/welcome_screen_bg_image.webp